Repository masters2023-2nd-project-traveler/todo-max, pull requests merged in 2023-07, with the labels that each got.

#21 [FE] chore: 기본 환경 세팅 작업 (#1)
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc.json
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/public/assets/icon_closed.svg
  fe/public/assets/icon_edit.svg
  fe/public/assets/icon_history.svg
  fe/public/assets/icon_plus.svg
  fe/public/mockServiceWorker.js
  fe/public/vite.svg
  fe/src/App.css
  fe/src/App.tsx
  fe/src/assets/react.svg
  fe/src/index.css
  fe/src/main.tsx
  fe/src/mocks/data/list.ts
  fe/src/mocks/handler.ts
  fe/src/mocks/worker.ts
  fe/src/styles/GlobalStyles.ts
  fe/src/styles/Theme.ts
  fe/src/vite-env.d.ts
  fe/tsconfig.json
  fe/tsconfig.node.json
  fe/vite.config.ts
Labels: FE, setting

#30 [FE] design: 버튼 UI 작업 (#23)
  fe/index.html
  fe/src/App.tsx
  fe/src/assets/icon_closed.svg
  fe/src/assets/icon_edit.svg
  fe/src/assets/icon_history.svg
  fe/src/assets/icon_plus.svg
  fe/src/components/Dummy.tsx
  fe/src/components/DummyTwo.tsx
  fe/src/components/buttons/Button.tsx
  fe/src/styles/GlobalStyles.ts
  fe/src/styles/Theme.ts
Labels: FE, ui

#31 [FE] design: 큰 레이아웃 UI 작업 (#29)
  fe/src/App.tsx
  fe/src/styles/GlobalStyles.ts
Labels: FE, ui

#33 [BE] docs: swagger 설정 (#4)
  be/travelers/build.gradle
  be/travelers/src/main/java/codesquad/todolist/travelers/config/SwaggerConfig.java
  be/travelers/src/main/resources/application.yml
Labels: BE, docs

#34 [FE] design: 헤더 UI 작업 (#24)
  fe/src/App.tsx
  fe/src/components/ActionHistory.tsx
  fe/src/components/Dummy.tsx
  fe/src/components/DummyTwo.tsx
  fe/src/components/HeaderTitle.tsx
Labels: FE, ui

#36 [FE] design: 카드 UI 작업 (#28)
  fe/src/components/card/Card.tsx
  fe/src/components/test.tsx
Labels: FE, ui

#39 [FE] design: 모달 UI 작업 (#26)
  fe/src/App.tsx
  fe/src/components/ActionHistory.tsx
  fe/src/components/ActionListItem.tsx
  fe/src/components/actionHistory/ActionHistory.tsx
  fe/src/components/actionHistory/ActionList.tsx
  fe/src/components/actionHistory/ActionListEmpty.tsx
  fe/src/components/actionHistory/ActionListItem.tsx
  fe/src/components/buttons/Button.tsx
  fe/src/components/card/Card.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/header/HeaderTitle.tsx
  fe/src/components/modal/Modal.tsx
  fe/src/styles/GlobalStyles.ts
Labels: FE, ui

#40 [FE] design: 칼럼 UI 작업 (#27)
  fe/src/App.tsx
  fe/src/components/card/Card.tsx
  fe/src/components/main/CardList.tsx
  fe/src/components/main/ColumnItem.tsx
  fe/src/components/main/ColumnList.tsx
  fe/src/components/main/ColumnTitle.tsx
  fe/src/components/test.tsx
  fe/src/main.tsx
  fe/src/mocks/data/list.ts
  fe/src/mocks/data/todolist.ts
  fe/src/mocks/handler.ts
  fe/src/styles/GlobalStyles.ts
Labels: FE, ui

#41 [BE] feat: 카드 등록, 조회를 위한 기능 구현 (#9) (#10)
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/ProcessResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/ResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/TaskRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/TaskResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/entity/Process.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/entity/Task.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/TaskRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
Labels: BE, feat

#43 [FE] refactor: 코딩 컨벤션 맞춤, 코드 정리 (#22)
  fe/src/App.tsx
  fe/src/components/Dummy.tsx
  fe/src/components/DummyTwo.tsx
  fe/src/components/actionHistory/ActionHistory.tsx
  fe/src/components/actionHistory/ActionList.tsx
  fe/src/components/actionHistory/ActionListEmpty.tsx
  fe/src/components/actionHistory/ActionListItem.tsx
  fe/src/components/buttons/Button.tsx
  fe/src/components/card/Card.tsx
  fe/src/components/header/HeaderTitle.tsx
  fe/src/components/main/CardList.tsx
  fe/src/components/main/ColumnList.tsx
  fe/src/components/main/ColumnTitle.tsx
  fe/src/components/modal/Modal.tsx
  fe/src/components/test.tsx
  fe/src/styles/GlobalStyles.ts
Labels: FE, refactor

#42 [BE] feat: 활동기록 삭제 API 구현 (#17)
  be/travelers/src/main/java/codesquad/todolist/travelers/history/controller/HistoryController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/repository/HistoryRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/repository/JdbcHistoryRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/service/HistoryService.java
Labels: BE, feat

#44 [BE] feat: 카드 삭제를 위한 기능 구현 + 버그 해결 (#11)
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/ResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/response/ProcessResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/response/TaskResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/entity/Task.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/TaskRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
Labels: BE, feat, refactor

#45 [BE] feat: 카드 삭제를 위한 기능 구현 (#12)
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskUpdateRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/TaskRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
Labels: BE, feat

#46 [BE] feat: 카드 이동을 위한 기능 구현 (#13)
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskProcessIdRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/response/TaskResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/TaskRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
Labels: BE, feat

#52 [FE] feat: 헤더 기능 작업 (#37)
  fe/index.html
  fe/src/components/actionHistory/ActionHistory.tsx
  fe/src/components/actionHistory/ActionList.tsx
  fe/src/components/buttons/Button.tsx
  fe/src/components/buttons/icon/Close.tsx
  fe/src/components/buttons/icon/Edit.tsx
  fe/src/components/buttons/icon/History.tsx
  fe/src/components/buttons/icon/Plus.tsx
  fe/src/components/modal/Modal.tsx
  fe/src/mocks/handler.ts
  fe/src/styles/GlobalStyles.ts
Labels: FE, feat

#48 [BE] feat: 활동 기록 조회를 위한 API 구현 (#18)
  be/travelers/src/main/java/codesquad/todolist/travelers/history/controller/HistoryController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/ActionHistory.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/dto/response/ActionHistoryResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/entity/History.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/repository/HistoryRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/repository/JdbcHistoryRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/service/HistoryService.java
  be/travelers/src/main/resources/application-prodDB.yml
  be/travelers/src/main/resources/application-testDB.yml
  be/travelers/src/main/resources/application.yml
  be/travelers/src/test/java/codesquad/todolist/travelers/annotation/ControllerTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/annotation/RepositoryTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/annotation/ServiceTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/history/controller/HistoryControllerTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/history/domain/repository/JdbcHistoryRepositoryImplTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/history/service/HistoryServiceTest.java
Labels: BE, feat, test

#53 [FE] feat: 카드 추가 관련 기능 (#47)
  fe/src/components/card/Card.tsx
  fe/src/components/main/AddModeCard.tsx
  fe/src/components/main/CardList.tsx
  fe/src/components/main/ColumnItem.tsx
  fe/src/components/main/ColumnList.tsx
  fe/src/components/main/ColumnTitle.tsx
  fe/src/mocks/handler.ts
Labels: FE, feat, refactor

#54 [FE] feat: 카드 삭제 기능 추가 (#51)
  fe/src/components/card/Card.tsx
  fe/src/components/main/CardList.tsx
  fe/src/mocks/handler.ts
Labels: FE, feat

#57 [BE] fix: Task와 taskId를 담는 TaskPostResponseDto 생성하여 응답 메시지 수정 (#55)
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/response/TaskPostResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
Labels: BE, feat, fix

#59 [FE] fix: 1주차 기능 합본 (#56)
  fe/src/components/main/CardList.tsx
Labels: FE, fix

#61 [BE] feat: TaskController에 Swagger 적용 (#60)
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
Labels: BE, feat

#65 [FE] fix: ts 오류 수정 (#64)
  fe/src/components/actionHistory/ActionList.tsx
  fe/src/components/actionHistory/ActionListItem.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/main/CardList.tsx
  fe/src/components/main/ColumnList.tsx
  fe/src/mocks/handler.ts
Labels: FE, fix

#63 [BE] 카드 관련 API 리팩터링 (#62)
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskUpdateRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/response/ProcessResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/response/TaskResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
Labels: BE, refactor

#66 [BE] 활동 기록 저장 기능 (#49)
  be/travelers/build.gradle
  be/travelers/src/main/java/codesquad/todolist/travelers/ActionType/ActionType.java
  be/travelers/src/main/java/codesquad/todolist/travelers/annotation/ActionId.java
  be/travelers/src/main/java/codesquad/todolist/travelers/aspect/HistoryLoggingAspect.java
  be/travelers/src/main/java/codesquad/todolist/travelers/aspect/dto/TaskServiceHistoryDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/entity/History.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/repository/HistoryRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/repository/JdbcHistoryRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/service/HistoryService.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/TaskRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
Labels: BE, feat

#68 [FE] refactor: 피드백 반영 및 코드 수정 (#64)
  fe/src/components/actionHistory/ActionHistory.tsx
  fe/src/components/actionHistory/ActionList.tsx
  fe/src/components/actionHistory/ActionListItem.tsx
  fe/src/components/buttons/Button.tsx
  fe/src/components/card/Card.tsx
  fe/src/components/main/AddModeCard.tsx
  fe/src/components/main/CardList.tsx
  fe/src/components/main/ColumnItem.tsx
  fe/src/components/main/ColumnList.tsx
  fe/src/components/modal/Modal.tsx
  fe/src/mocks/data/todolist.ts
Labels: FE, fix, refactor

#72 [BE] 글로벌 커스텀 status code 형식 완성 (#67)
  be/travelers/src/main/java/codesquad/todolist/travelers/global/ApiResponse.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/CustomException.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/ErrorCode.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/GlobalExceptionHandler.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/StatusCode.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/SuccessCode.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/repository/HistoryRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/repository/JdbcHistoryRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/service/HistoryService.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskUpdateRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/TaskRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
Labels: BE, feat

#74 [BE] 컬럼 생성 API 구현 (#15)
  be/travelers/src/main/java/codesquad/todolist/travelers/global/ErrorCode.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/SuccessCode.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/service/HistoryService.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/controller/ProcessController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/dto/ProcessRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/entity/Process.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/repository/JdbcProcessRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/repository/ProcessRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/service/ProcessService.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/response/TasksByProcessResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/TaskRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
Labels: BE, feat

#70 [FE] 히스토리 카드 todo데이터와 연동 (#69)
  fe/.eslintrc.json
  fe/src/App.tsx
  fe/src/components/actionHistory/ActionList.tsx
  fe/src/components/main/ColumnItem.tsx
  fe/src/components/main/ColumnList.tsx
  fe/src/contexts/DataContext.tsx
Labels: FE, fix

#75 [FE] feat: 카드 수정 기능 구현 (#50)
  fe/src/components/card/Card.tsx
  fe/src/components/main/CardList.tsx
  fe/src/components/main/ColumnItem.tsx
  fe/src/components/main/ColumnList.tsx
  fe/src/mocks/handler.ts
Labels: FE, feat

#76 [BE] feat: 칼럼 수정 api 구현 (#14)
  be/travelers/src/main/java/codesquad/todolist/travelers/global/ErrorCode.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/controller/ProcessController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/entity/Process.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/repository/JdbcProcessRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/repository/ProcessRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/service/ProcessService.java
Labels: BE, feat

#77 [BE] feat: 칼럼 삭제 api 구현 (#16)
  be/travelers/src/main/java/codesquad/todolist/travelers/global/ApiResponse.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/CommonApiResponse.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/GlobalExceptionHandler.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/controller/HistoryController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/controller/ProcessController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/dto/ProcessRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/repository/JdbcProcessRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/repository/ProcessRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/service/ProcessService.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
Labels: BE, feat

#80 [BE] test: 단위 테스트 코드 작성 (#73)
  be/travelers/src/main/java/codesquad/todolist/travelers/global/CommonApiResponse.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/controller/HistoryController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/test/java/codesquad/todolist/travelers/annotation/RepositoryTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/history/controller/HistoryControllerTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/history/domain/repository/JdbcHistoryRepositoryImplTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/controller/TaskControllerTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImplTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/service/TaskServiceTest.java
  be/travelers/src/test/resources/schema.sql
Labels: BE, test

#79 [FE] 선택 사항 구현
  fe/src/App.tsx
  fe/src/components/actionHistory/ActionHistory.tsx
  fe/src/components/actionHistory/ActionList.tsx
  fe/src/components/actionHistory/ActionListItem.tsx
  fe/src/components/buttons/Button.tsx
  fe/src/components/main/CardList.tsx
  fe/src/components/main/ColumnItem.tsx
  fe/src/components/main/ColumnList.tsx
  fe/src/components/main/ColumnTitle.tsx
  fe/src/components/main/FloatingAction.tsx
  fe/src/main.tsx
  fe/src/mocks/handler.ts
  fe/src/styles/GlobalStyles.ts
Labels: FE, feat

#82 [BE] refactor: AOP 리팩토링 (#81)
  be/travelers/src/main/java/codesquad/todolist/travelers/aspect/HistoryLoggingAspect.java
  be/travelers/src/main/java/codesquad/todolist/travelers/aspect/PointCuts.java
  be/travelers/src/main/java/codesquad/todolist/travelers/aspect/dto/TaskServiceHistoryDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/service/HistoryService.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/service/ProcessService.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/TaskRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/controller/TaskControllerTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImplTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/service/TaskServiceTest.java
  be/travelers/src/test/resources/schema.sql
Labels: BE, refactor

#84 [BE] feat: 카드 이동시 정렬 기능 구현 및 리팩토링 (#83)
  be/travelers/src/main/java/codesquad/todolist/travelers/actionType/ActionType.java
  be/travelers/src/main/java/codesquad/todolist/travelers/annotation/ActionId.java
  be/travelers/src/main/java/codesquad/todolist/travelers/aspect/dto/TaskServiceHistoryDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/ErrorCode.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/GlobalExceptionHandler.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/StatusCode.java
  be/travelers/src/main/java/codesquad/todolist/travelers/global/SuccessCode.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/controller/HistoryController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/repository/HistoryRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/service/HistoryService.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/controller/ProcessController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/domain/repository/ProcessRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/controller/TaskController.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskMoveRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskProcessIdRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/request/TaskUpdateRequestDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/dto/response/TaskResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/entity/Task.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/domain/repository/TaskRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
  be/travelers/src/test/java/codesquad/todolist/travelers/history/controller/HistoryControllerTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/controller/TaskControllerTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImplTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/service/TaskServiceTest.java
  be/travelers/src/test/resources/schema.sql
Labels: BE, feat

#85 [FE] 오류 수정 (#78)
  fe/src/components/actionHistory/ActionList.tsx
  fe/src/components/actionHistory/ActionListItem.tsx
  fe/src/components/main/AddModeCard.tsx
  fe/src/components/main/CardList.tsx
  fe/src/components/main/ColumnItem.tsx
  fe/src/components/main/ColumnList.tsx
  fe/src/components/main/ColumnTitle.tsx
  fe/src/components/main/FloatingAction.tsx
  fe/src/mocks/handler.ts
Labels: FE, fix

#89 [BE] test: 테스트코드 추가 작성 (#88)
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/dto/response/ActionHistoryResponseDto.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/domain/vo/ActionHistory.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/repository/HistoryRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/repository/JdbcHistoryRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/history/service/HistoryService.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/repository/JdbcProcessRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/repository/ProcessRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/process/service/ProcessService.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/repository/JdbcTaskRepositoryImpl.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/repository/TaskRepository.java
  be/travelers/src/main/java/codesquad/todolist/travelers/task/service/TaskService.java
  be/travelers/src/test/java/codesquad/todolist/travelers/history/controller/HistoryControllerTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/history/domain/repository/JdbcHistoryRepositoryImplTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/history/service/HistoryServiceTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/domain/repository/JdbcTaskRepositoryImplTest.java
  be/travelers/src/test/java/codesquad/todolist/travelers/task/service/TaskServiceTest.java
Labels: BE, test

#91 [FE] fix: 대문자 소문자로 수정 (#90)
  fe/src/components/main/AddModeCard.tsx
  fe/src/components/main/ColumnList.tsx
  fe/src/mocks/handler.ts
Labels: FE, fix, refactor
